### ISSUE TITLE
Seems to work?

### ISSUE THREAD

**Issue by zvavybir** [Dummi26/rust_wasm_test_game#1]
It's seems to me like everything is working as it should.  Where is the slow code?

**Comment by Dummi26** [comment]
It actually does work. I downloaded everything from github and saved it in a different folder, recompiled it and it performs just fine. After running cargo clean and rebuilding everything in my old folder (where it performed about 10x slower before), this now also works fine.

**Comment by zvavybir** [comment]
That's awesome! :smile:
